# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main  # Trigger the pipeline on changes to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use a Linux-based VM image (you can change this to 'windows-latest' or 'macos-latest' if needed)

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
    - job: BuildJob
      displayName: 'Build Job'
      steps:
        - checkout: self

        - task: NodeTool@0
          inputs:
            versionSpec: '16.x'  # Specify the version of Node.js (you can change this as needed)
          displayName: 'Install Node.js'

        - task: npm@1
          inputs:
            command: 'install'  # Install dependencies from package.json
          displayName: 'Install dependencies'

        - task: XplatGenerateReleaseNotes@4
          displayName: 'Generate Release Notes'
          inputs:
            outputfile: '$(Build.ArtifactStagingDirectory)/releasenotes.md'  # Path to output the release notes file
            templateLocation: 'inline'  # Use an inline template for generating the release notes
            customHandlebarsExtensionCode: |
              ## Build {{buildDetails.buildNumber}}
              * **Branch**: {{buildDetails.sourceBranch}}
              * **Tags**: {{buildDetails.tags}}
              * **Completed**: {{buildDetails.finishTime}}
              * **Previous Build**: {{compareBuildDetails.buildNumber}}

              ## Associated Pull Requests ({{pullRequests.length}})
              {{#if pullRequests.length}}
                {{#forEach pullRequests}}
                  * **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** {{this.title}}
                  * Associated Work Items
                  {{#if this.associatedWorkitems.length}}
                    {{#forEach this.associatedWorkitems}}
                      {{#with (lookup_a_work_item ../../relatedWorkItems this.url)}}
                        - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}}
                      {{/with}}
                    {{/forEach}}
                  {{else}}
                    No associated work items.
                  {{/if}}
                  * Associated Commits
                  {{#if this.associatedCommits.length}}
                    {{#forEach this.associatedCommits}}
                      - [{{this.commitId}}]({{this.remoteUrl}}) -  {{this.comment}}
                    {{/forEach}}
                  {{else}}
                    No associated commits.
                  {{/if}}
                {{/forEach}}
              {{else}}
                No pull requests found.
              {{/if}}
              
              ## Associated Commits
              {{#forEach commits}}
                - [{{this.commitId}}]({{this.remoteUrl}}) -  {{this.comment}}
              {{/forEach}}

              ## Related Work Items
              {{#if relatedWorkItems.length}}
                {{#forEach relatedWorkItems}}
                  - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}}
                {{/forEach}}
              {{else}}
                No related work items.
              {{/if}}
            # You can add more parameters here to customize the release notes

        - publish: $(Build.ArtifactStagingDirectory)/releasenotes.md  # Publish the release notes as an artifact
          artifact: releaseNotes
          displayName: 'Publish Release Notes Artifact'

        # Add other build tasks like linting, building, and testing here
        - task: npm@1
          inputs:
            command: 'custom'  # Run tests (adjust this based on your project)
            customCommand: 'test'
          displayName: 'Run Tests'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
    - job: DeployJob
      displayName: 'Deploy Job'
      steps:
        - download: current  # Download artifacts from the Build stage
          artifact: releaseNotes
          displayName: 'Download Release Notes Artifact'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact'
          inputs:
            artifactName: 'releaseNotes'
            targetPath: '$(Pipeline.Workspace)/releaseNotes'

